# Generated by Django 2.0.4 on 2018-04-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180423_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название главы'),
        ),
    ]
