# Generated by Django 2.0.4 on 2018-04-29 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20180429_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='lesson',
        ),
        migrations.AlterUniqueTogether(
            name='usertest',
            unique_together={('test', 'user')},
        ),
    ]
