# Generated by Django 2.0.4 on 2018-04-29 18:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20180429_1754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTest',
            new_name='TestUser',
        ),
    ]
