# Generated by Django 2.0.4 on 2018-04-29 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20180429_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='testuser',
            name='status',
            field=models.IntegerField(choices=[(0, 'В процессе'), (1, 'Закончен')], default=0, verbose_name='Статус теста'),
        ),
        migrations.AddField(
            model_name='userlesson',
            name='status',
            field=models.IntegerField(choices=[(0, 'В процессе'), (1, 'Закончен')], default=0, verbose_name='Статус теста'),
        ),
        migrations.AlterUniqueTogether(
            name='userlesson',
            unique_together={('lesson', 'user')},
        ),
    ]
