# Generated by Django 2.0.4 on 2018-04-29 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180429_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_word', models.CharField(max_length=255, verbose_name='Слово на английском')),
                ('ru_word', models.CharField(max_length=255, verbose_name='Слово на русском')),
                ('note', models.TextField(verbose_name='Заметка')),
            ],
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='en_word',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='note',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='ru_word',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='title',
            field=models.CharField(default='Мой словарь', max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='word',
            name='dictionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dictionary'),
        ),
    ]
